version: '3.8'
services:
  app:
    build: .
    ports:
      - 5005:5005
    environment:
      - PORT=5005
      - DB_URL=mongodb://db:27017/cx-trade-api
    depends_on:
      - db
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=cx-trade-api
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: {}